pElectrospark = ParticleType.new("Electrospark")
pElectrospark:shape("pixel")
pElectrospark:color(Color.WHITE, Color.lighten(Color.YELLOW, 0.5))
pElectrospark:alpha(1, 0)
pElectrospark:additive(true)
pElectrospark:speed(3, 5, 0, 0)
pElectrospark:direction(90 - 30, 90 + 30, 0, 0)
pElectrospark:gravity(0.5, 270)
pElectrospark:life(60 * 0.2, 60 * 0.3)